# Generated by Django 4.1.4 on 2023-03-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100, verbose_name='post')),
                ('surname', models.CharField(max_length=25, verbose_name='surname')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('patronymic', models.CharField(max_length=25, verbose_name='patronymic')),
                ('rank', models.IntegerField(max_length=11, verbose_name='rank')),
                ('extension_number', models.CharField(max_length=25, verbose_name='extension_number')),
                ('landline_number', models.CharField(max_length=25, verbose_name='landline_number')),
                ('department', models.IntegerField(max_length=11, verbose_name='department')),
            ],
            options={
                'db_table': 'abonents',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('parent_id', models.IntegerField(max_length=11, verbose_name='parent_id')),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=25, verbose_name='rank')),
            ],
            options={
                'db_table': 'ranks',
            },
        ),
    ]
